export const FIREBASE_INITIALIZE = "FIREBASE_INITIALIZE";
export const FIREBASE_INITIALIZE_SUCCESS = "FIREBASE_INITIALIZE_SUCCESS";
export const FIREBASE_CHECK_PREVSIGNEDINUSER = "FIREBASE_CHECK_PREVSIGNEDINUSER";
export const FIREBASE_CHECK_PREVSIGNEDINUSER_SUCCESS = "FIREBASE_CHECK_PREVSIGNEDINUSER_SUCCESS";
export const FIREBASE_GITHUBSIGNIN_FAILURE = "FIREBASE_GITHUBSIGNIN_FAILURE";
export const FIREBASE_SIGNIN_SUCCESS = "FIREBASE_SIGNIN_SUCCESS";
export const FIREBASE_FACEBOOKSIGNIN_FAILURE = "FIREBASE_FACEBOOKSIGNIN_FAILURE";
export const FIREBASE_SIGNOUT = "FIREBASE_SIGNOUT";
export const FIREBASE_SIGNOUT_SUCCESS = "FIREBASE_SIGNOUT_SUCCESS";
export const FIREBASE_SIGNUP = "FIREBASE_SIGNUP";
export const FIREBASE_SUBSCRIBE_IDTOKEN = "FIREBASE_SUBSCRIBE_IDTOKEN";
export const FIREBASE_UNSUBSCRIBE_IDTOKEN = "FIREBASE_UNSUBSCRIBE_IDTOKEN";
export const FIREBASE_IDTOKEN_UPDATED = "FIREBASE_IDTOKEN_UPDATED";

export const USER_SIGNIN = "USER_SIGNIN";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAILURE = "USER_SIGNIN_FAILURE";

export const FETCH_TILLIST = "FETCH_TILLIST";
export const FETCH_TILLIST_SUCCESS = "FETCH_TILLIST_SUCCESS";
export const FETCH_TILLIST_ERROR = "FETCH_TILLIST_ERROR";
