export const FIREBASE_INITIALIZED_SUCCESS = "FIREBASE_INITIALIZED_SUCCESS";
export const FIREBASE_LOAD_SIGNEDINUSER = "FIREBASE_LOAD_SIGNEDINUSER";
export const FIREBASE_LOAD_SIGNEDINUSER_SUCCESS = "FIREBASE_LOAD_SIGNEDINUSER_SUCCESS";
export const FETCH_TILLIST = "FETCH_TILLIST";
export const FETCH_TILLIST_SUCCESS = "FETCH_TILLIST_SUCCESS";
export const FETCH_TILLIST_ERROR = "FETCH_TILLIST_ERROR";
